# Generated by Django 6.1.1 on 2026-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('choice', '选择题'), ('blank', '填空题'), ('short', '简答题'), ('practical', '实战操作题')], db_index=True, max_length=16)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer', models.JSONField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
