# Generated by Django 6.1.1 on 2026-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='来源文档'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(db_index=True, max_length=64, verbose_name='知识点分类'),
        ),
        migrations.CreateModel(
            name='QuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, verbose_name='作答次数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对次数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='答错次数')),
                ('wrong_streak', models.IntegerField(default=0, verbose_name='连续答错')),
                ('in_wrongbook', models.BooleanField(db_index=True, default=False, verbose_name='在错题本中')),
                ('last_correct', models.BooleanField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='quizapp.question')),
            ],
            options={
                'verbose_name': '题目作答统计',
            },
        ),
    ]
