# Generated by Django 6.1.1 on 2026-09-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_question_source_alter_question_category_questionstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('exam', '考试模式')], db_index=True, max_length=16)),
                ('scope', models.JSONField(default=dict)),
                ('total', models.IntegerField(default=0, verbose_name='题目总数')),
                ('graded', models.IntegerField(default=0, verbose_name='客观判分题数')),
                ('correct', models.IntegerField(default=0, verbose_name='客观答对题数')),
                ('subjective', models.IntegerField(default=0, verbose_name='主观题数')),
                ('score', models.FloatField(default=0, verbose_name='得分率%')),
                ('duration_s', models.IntegerField(default=0, verbose_name='用时(秒)')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='交卷时间')),
            ],
            options={
                'verbose_name': '训练档案',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='starred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='星标收藏'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='quizapp.question')),
            ],
        ),
    ]
