# Generated by Django 6.1.1 on 2026-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_trainingsession_question_starred_note'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source', 'type'], name='idx_q_source_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'type'], name='idx_q_cat_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source', 'category'], name='idx_q_source_cat'),
        ),
        migrations.AddIndex(
            model_name='questionstat',
            index=models.Index(fields=['in_wrongbook', '-updated_at'], name='idx_stat_wb_recent'),
        ),
    ]
